# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/zhaodejin/Documents/Workspace/c++ForComputer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/zhaodejin/Documents/Workspace/c++ForComputer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/zhaodejin/Documents/Workspace/c++ForComputer/CMakeFiles /Users/zhaodejin/Documents/Workspace/c++ForComputer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/zhaodejin/Documents/Workspace/c++ForComputer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named c++ForComputer

# Build rule for target.
c++ForComputer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 c++ForComputer
.PHONY : c++ForComputer

# fast build rule for target.
c++ForComputer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c++ForComputer.dir/build.make CMakeFiles/c++ForComputer.dir/build
.PHONY : c++ForComputer/fast

src/utils/logger.o: src/utils/logger.cpp.o
.PHONY : src/utils/logger.o

# target to build an object file
src/utils/logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c++ForComputer.dir/build.make CMakeFiles/c++ForComputer.dir/src/utils/logger.cpp.o
.PHONY : src/utils/logger.cpp.o

src/utils/logger.i: src/utils/logger.cpp.i
.PHONY : src/utils/logger.i

# target to preprocess a source file
src/utils/logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c++ForComputer.dir/build.make CMakeFiles/c++ForComputer.dir/src/utils/logger.cpp.i
.PHONY : src/utils/logger.cpp.i

src/utils/logger.s: src/utils/logger.cpp.s
.PHONY : src/utils/logger.s

# target to generate assembly for a file
src/utils/logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c++ForComputer.dir/build.make CMakeFiles/c++ForComputer.dir/src/utils/logger.cpp.s
.PHONY : src/utils/logger.cpp.s

src/utils/main.o: src/utils/main.cpp.o
.PHONY : src/utils/main.o

# target to build an object file
src/utils/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c++ForComputer.dir/build.make CMakeFiles/c++ForComputer.dir/src/utils/main.cpp.o
.PHONY : src/utils/main.cpp.o

src/utils/main.i: src/utils/main.cpp.i
.PHONY : src/utils/main.i

# target to preprocess a source file
src/utils/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c++ForComputer.dir/build.make CMakeFiles/c++ForComputer.dir/src/utils/main.cpp.i
.PHONY : src/utils/main.cpp.i

src/utils/main.s: src/utils/main.cpp.s
.PHONY : src/utils/main.s

# target to generate assembly for a file
src/utils/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c++ForComputer.dir/build.make CMakeFiles/c++ForComputer.dir/src/utils/main.cpp.s
.PHONY : src/utils/main.cpp.s

src/utils/utils.o: src/utils/utils.cpp.o
.PHONY : src/utils/utils.o

# target to build an object file
src/utils/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c++ForComputer.dir/build.make CMakeFiles/c++ForComputer.dir/src/utils/utils.cpp.o
.PHONY : src/utils/utils.cpp.o

src/utils/utils.i: src/utils/utils.cpp.i
.PHONY : src/utils/utils.i

# target to preprocess a source file
src/utils/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c++ForComputer.dir/build.make CMakeFiles/c++ForComputer.dir/src/utils/utils.cpp.i
.PHONY : src/utils/utils.cpp.i

src/utils/utils.s: src/utils/utils.cpp.s
.PHONY : src/utils/utils.s

# target to generate assembly for a file
src/utils/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c++ForComputer.dir/build.make CMakeFiles/c++ForComputer.dir/src/utils/utils.cpp.s
.PHONY : src/utils/utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... c++ForComputer"
	@echo "... src/utils/logger.o"
	@echo "... src/utils/logger.i"
	@echo "... src/utils/logger.s"
	@echo "... src/utils/main.o"
	@echo "... src/utils/main.i"
	@echo "... src/utils/main.s"
	@echo "... src/utils/utils.o"
	@echo "... src/utils/utils.i"
	@echo "... src/utils/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

